require 'fileutils'
require 'active_support/inflector'
require 'tillless-baton/version'
require 'tillless-baton/concepts/merchant_config'

module Baton
  class Orchestrator
    attr_accessor :config

    def initialize(config)
      @config = config # is_a? Baton::MerchantConfig
      setup
    end

    def setup
      @setup  = true
      @output = <<EOF
# This file was generated by Baton: http://github.com/tillless/baton
EOF
    end

    def orchestrate
      setup if !@setup
      @output
    end

  end
end
